### ISSUE TITLE
Lower screen resolution menu issues

### ISSUE THREAD

**Issue by brettalcox** [JBakamovic/yavide#19]
On a lower screen res such as 1280x800, when selecting a compiler (or any menu option with a long list) from the menu, the menu extends past the bottom of the screen.

**Comment by JBakamovic** [comment]
I am not sure what you mean by menu extending past the bottom of the screen? If entries from the list cannot fit to the display height, then you should be provided with arrows at the top and bottom of the list which enable you to traverse through the entries. Attached is the image depicting how it looks like on my machine with the resolution set to 1280x800 and I find this behavior perfectly fine:
![long_menu_screenshot](https://cloud.githubusercontent.com/assets/7620680/6213331/db667806-b5ee-11e4-9bc5-c2411ea0e036.png)

**Comment by brettalcox** [comment]
This is on Linux.
![2015-02-16-085116_1280x800_scrot](https://cloud.githubusercontent.com/assets/7462622/6213812/3c0206fc-b5b9-11e4-9848-aafff76c2a1e.png)

**Comment by brettalcox** [comment]
Okay much better now. I recompiled with +gtk support. Could you add that in the README? I compiled with only Python and Gnome flags initially, which is what led to the ncurses ui. Adding gtk flag properly loads ui as expected

**Comment by JBakamovic** [comment]
That's what I was about to comment. This doesn't look like Gtk-based Vim at all. I will put this additional info in README to be more concise. Thanks.
