### ISSUE TITLE
Navigation through "history" in shell using arrow keys produces strange symbols.

### ISSUE THREAD

**Issue by brettalcox** [JBakamovic/yavide#21]
![2015-02-16-225829_1280x800_scrot](https://cloud.githubusercontent.com/assets/7462622/6223470/eb370d36-b62f-11e4-898f-d65485fddada.png)

**Comment by JBakamovic** [comment]
This is not an issue of `Yavide` per se but of `GVim`. You can check that by running the very same commands in plain `GVim` instance and you will observe the same misbehavior.

It seems that this is a known bug. I.e. see this: 
* http://superuser.com/questions/80730/why-dont-the-up-down-arrows-work-while-executing-a-shell-command-from-within-g

I haven't really delved into the topic so I am currently not aware if it can be fixed.
