### ISSUE TITLE
install should display package manager commands before executing them

### ISSUE THREAD

**Issue by wichtounet** [JBakamovic/yavide#26]
Hi, 

I'm on Gentoo. I tried to install with install.sh script. I entered my password for sudo, but then, it tried to update my Gentoo packages without any confirmation and tried to downgrade some of my packages. Doing an `emerge -uv world` should not be done by the script or at least the ask (-a) option should be used. 

I think that the install script does too much. There should be at least an option to make a minimal install.

**Comment by JBakamovic** [comment]
Minimal install of what? All packages being installed by the install script are **required** for features offered by `yavide` to function properly. So, there are no additional packages or whatsoever being installed without the reason ...

This install script is here for convenience ... What a convenience would be if script halted a user for every single dependency which is missing? Even for a trivial operation like updating the system package repositories? Purpose of this script is exactly that, to install the missing dependencies and relieve the user from doing the same thing by hand.

If you feel uncomfortable about the script, feel free to install those dependencies manually. It is not hard to enumerate them by quickly skimming through the script.

**Comment by wichtounet** [comment]
For the dependencies, it can be a good thing, but even if it is convenient, I personally don't trust a script with my package manager. 

> Even for a trivial operation like updating the system package repositories? Purpose of this script is exactly that, to install the missing dependencies and relieve the user from doing the same thing by hand.

But, that is not what the script is doing, at least for Gentoo! If you want to update package repositories, you have to use `emerge --sync`. What you are doing is doing an update of the packages themselves. In my case, it triggered the update of flash, several system libraries, firefox, .... That is what I don't find normal.

**Comment by JBakamovic** [comment]
> If you want to update package repositories, you have to use emerge --sync. What you are doing is doing an update of the packages themselves.

Ok, thank you for the fix. I was not aware of this.
