### ISSUE TITLE
Error detected while processing function Y_Env_Init

### ISSUE THREAD

**Issue by yilongli** [JBakamovic/yavide#28]
After a successful installation, I get the following error message during the startup process:
![screenshot from 2015-07-13 20 51 04](https://cloud.githubusercontent.com/assets/4922997/8650479/a4a2ec2a-29a5-11e5-90be-1b8801a4e9f7.png)

Adding ```import os``` at the beginning of ```core/indexer/yavide_indexer_if.py``` seems to solve the problem for me. Any idea what is wrong with my installation? Thanks!

**Comment by JBakamovic** [comment]
Thanks, this is fixed now. As you noted, `os` dependency was indeed missing from the package import list. But I find it very puzzling that it worked and still works on my machine even without this import. Probably something to do with local `python` configuration or with `python` having preload some of the packages.

**Comment by javierfileiv** [comment]
I'm having the same issue when starting up yavide. It's a recently clone so this issue should be fixed. Also, the indexer folder doesn;t even exist.

Thanks

**Comment by JBakamovic** [comment]
Please attach the error messages you get.

**Comment by javierfileiv** [comment]
![screenshot - 21102016 - 08 58 36](https://cloud.githubusercontent.com/assets/587023/19589480/a8be6cae-976c-11e6-822d-ea140112ff29.png)

**Comment by JBakamovic** [comment]
Strange that there are no other more specific error messages. I can't really tell much from the screenshot but than this is the python code which is being executed. Which distro are you running?

You mentioned that you don't even have indexer folder in your installation directory? Did you clone repository properly?

**Comment by javierfileiv** [comment]
yes, sure...I followed all the steps. Ubuntu 14 is my distro. How can I get
you more logs?

Thanks!

2016-10-21 9:20 GMT+02:00 Jusufadis Bakamovic <notifications@github.com>:

**Comment by JBakamovic** [comment]
`/tmp/YAVIDE_server.log` is the log file you can have a look at. You can attach it here as well.

**Comment by heefan** [comment]
**25 Aug 2017**
I have the same problem as well. 
The installation is following the installation guide. 

Environment:  Ubuntu 16.04
![screenshot from 2017-08-25 10-06-41](https://user-images.githubusercontent.com/892641/29696832-e43f9772-897d-11e7-8df1-35ace02507ec.png)

I could not find out the log file `/tmp/YAIDE_server.log`, as the file does not exist.

**Comment by JBakamovic** [comment]
For some reason `watchdog` Python module seems not to be installed. Can you try installing it manually with pip? `pip install watchdog`

**Comment by heefan** [comment]
Cool. My problem solved after installing watchdog.
Thanks & Thanks for your IDE. :)
