### ISSUE TITLE
Uninstall??

### ISSUE THREAD

**Issue by TheAifam5** [JBakamovic/yavide#30]
Very nice.. but how to uninstall this? Really that must be hard?

**Comment by JBakamovic** [comment]
It's not hard. It's lack of time. Feel free to contribute if you feel so.

**Comment by Queuecumber** [comment]
Can you please elaborate on the uninstallation instructions?

**Comment by LorenzoPetite** [comment]
Hi there, I'd really appreciate uninstall instructions.

If it's not hard, care to take five minutes to explain so I don't miss anything?

I haven't even tried the software yet, I just need to start again because I messed up the install.

**Comment by JBakamovic** [comment]
See #68
