### ISSUE TITLE
Source code auto-complete not working

### ISSUE THREAD

**Issue by liscju** [JBakamovic/yavide#31]
I have succesfully installed yavide, open project and everything except this works. Clang is installed, libclang.so is set properly in .user_settings.vimrc, but .clang_complete file is empty. My OS is lubuntu 15.04 desktop amd64

**Comment by JBakamovic** [comment]
You need to fill in the relevant data in `.clang_complete` file, that is include paths that you use in your project so `clang_complete` can utilize them while assisting you in code auto-complete. For further information you should have a look at [`clang_complete` docs](https://github.com/Rip-Rip/clang_complete/blob/master/doc/clang_complete.txt).

It would be handy to generate these entries automatically if possible but as of now there is no such support in `Yavide`.

**Comment by liscju** [comment]
Thanks for quick response. From what i read .clang_complete containing CFLAGS to gcc should be enough, but its not. For now i have very simple directory structure which contains all headers files and implementation files in main directory tree. It looks like this: 
https://github.com/liscju/SimpleOS
nothing fancy here iso/boot dir is only for output. Probably you are not person i should ask to guide how .clang_complete should look like for such a simple project but i give it a try :P

**Comment by JBakamovic** [comment]
From what I know, `clang_complete` basically expects include paths that you would normally pass to your compiler through your build system (i.e. `make`) in order to build your stuff successfully. In your case I think that `.clang_complete` file, if it's in your root directory, would consist of single entry which is `./`

**Comment by liscju** [comment]
As you suggested i put "./" in .clang_complete file and now autocompletion shows with <TAB> correctly. Many thanks for taking your time for vim novice user, issue can be closed

**Comment by JBakamovic** [comment]
It was my pleasure.

**Comment by liscju** [comment]
A little thing more: sometimes after adding new symbol going to definition is not working, how can i manually refresh ctags?

**Comment by JBakamovic** [comment]
Can you please open a new ticket regarding this issue? Generally, this shouldn't be happening under normal circumstances. Also provide some more details please. 

I.e.
* In what way are you trying to jump to definition (pressing `F12` or some other way?)?
* Did you save the file where you added a new symbol?
* Make sure that indexer is running fine in the background (if not please report it to me) by checking the output of `ps -aux | grep yavide_indexer`. You should see something like `python /opt/yavide/core/indexer/yavide_indexer.py 6000`.
