### ISSUE TITLE
This just aint working on  Ubuntu15.10

### ISSUE THREAD

**Issue by kurazsi** [JBakamovic/yavide#41]
in order to run vim whit this i need to always use:
vim -u /opt/yavide/.vimrc
and this gives a lot of errors

╰─$ vim -u /opt/yavide/.vimrc 
Error detected while processing /opt/yavide/.vimrc:
line   10:
E697: Missing end of List ']': 
E15: Invalid expression: [
line   11:
E10: \ should be followed by /, ? or &
line   12:
E10: \ should be followed by /, ? or &
line   13:
E10: \ should be followed by /, ? or &
line   14:
E10: \ should be followed by /, ? or &
line   15:
E10: \ should be followed by /, ? or &
line   16:
E10: \ should be followed by /, ? or &
line   17:
E10: \ should be followed by /, ? or &
line   18:
E10: \ should be followed by /, ? or &
line   19:
E10: \ should be followed by /, ? or &
line   21:
E121: Undefined variable: g:yavide_configuration_files
E15: Invalid expression: g:yavide_configuration_files
Error detected while processing /home/kurazsi/.vim/plugin/clang_complete.vim:
line  246:
E15: Invalid expression: 
E15: Invalid expression: {
line  247:
E10: \ should be followed by /, ? or &
line  248:
E10: \ should be followed by /, ? or &
line  249:
E10: \ should be followed by /, ? or &
line  250:
E10: \ should be followed by /, ? or &
line  251:
E10: \ should be followed by /, ? or &
line  252:
E10: \ should be followed by /, ? or &
line  253:
E10: \ should be followed by /, ? or &
line  254:
E10: \ should be followed by /, ? or &
line  255:
E10: \ should be followed by /, ? or &
line  256:
E10: \ should be followed by /, ? or &
line  257:
E10: \ should be followed by /, ? or &
line  258:
E10: \ should be followed by /, ? or &
line  259:
E10: \ should be followed by /, ? or &
line  260:
E10: \ should be followed by /, ? or &
line  261:
E10: \ should be followed by /, ? or &
line  262:
E10: \ should be followed by /, ? or &
line  263:
E10: \ should be followed by /, ? or &
line  266:
E121: Undefined variable: s:flagInfo
E116: Invalid arguments for function values(s:flagInfo)
E15: Invalid expression: values(s:flagInfo)
Press ENTER or type command to continue

after i fix the above....
i get this:
╰─$ vim -u /opt/yavide/.vimrc
Error detected while processing /opt/yavide/core/.core.vimrc:
line   18:
E117: Unknown function: pathogen#infect
E15: Invalid expression: pathogen#infect(g:YAVIDE_ROOT_DIRECTORY                                   . '/' . '{}',g:YAVIDE_ROOT_DIRECTORY . '/' . 'colors'                  . '/' . '{}',g:YAVIDE_ROOT_DIRECTORY . '/' . 'config'                  . '/' . '{}',g:YAVIDE_ROOT_DIRECTORY . '/' . 'core'                    . '/' . '{}',g:YAVIDE_ROOT_DIRECTORY . '/' . 'core' . '/' . 'common'   . '/' . '{}',g:YAVIDE_ROOT_DIRECTORY . '/' . 'core' . '/' . 'external' . '/' . '{}',g:YAVIDE_ROOT_DIRECTORY . '/' . 'core' . '/' . 'indexer'  . '/' . '{}',g:YAVIDE_ROOT_DIRECTORY . '/' . 'core' . '/' . 'ui'       . '/' . '{}')
Error detected while processing /opt/yavide/core/.editor.vimrc:
line   38:
E185: Cannot find color scheme 'wombat256'
Press ENTER or type command to continue

leading me to the conclusion that this project is broken...

**Comment by JBakamovic** [comment]
First of all, next time try to be more polite while communicating problems to open source projects such as this one. Normally I would have ignored reports made in this kind of tone ...

Second of all, project is not broken but the way you are trying to run the `Yavide` environment is broken. I don't know where did you get the idea that it should be run with `vim -u /opt/yavide/.vimrc` ?!

If you prefer to run it from the command line, you should simply use `yavide` and if you prefer to run it from GUI you have a choice of `Desktop` icon, `Unity`/`Gnome` launcher or whatever that is aligned with the philosophy of `freedesktop.org` application entries.
