### ISSUE TITLE
No effect

### ISSUE THREAD

**Issue by Andimeo** [JBakamovic/yavide#42]
Hi, what should I do after I install yavide?
Seems only following the instructions doesn't take any effect at all?

**Comment by JBakamovic** [comment]
You have 3 choices:
* Use `yavide` icon from the desktop
* Use start menu and find `yavide` under development/programming 
* Use Unity/Gnome launcher and find it by typing `yavide`

**Comment by Andimeo** [comment]
Thank you! What does "ctrl-s i" mean?
I want to import an existed project by holding ctrl and s down then press i, nothing happns except I entered into insert mode. What should I do?

**Comment by JBakamovic** [comment]
`ctrl-s i` creates a new `yavide` project from your existing source code. You are probably not doing it well ... try pressing `ctrl-s` and quickly afterwards press `i`. Do not hold `ctrl-s` while pressing `i`.

You also have an option of using pure commands if you find them more convenient than keyboard shortcuts. I.e. `ctrl-s i` can be done by using `YavideProjectImport` command. List of all commands you will find in `<yavide_install_dir>/core/.commands.vimrc`. Moreover, you can redefine keyboard shortcuts to your liking by editing the `<yavide_install_dir>/config/after/plugin/keyboard.vim`.
