### ISSUE TITLE
How to make it look like the screenshot

### ISSUE THREAD

**Issue by ckubrak** [JBakamovic/yavide#47]
Hi
I've just installed yavide and it looks like this:
http://imgur.com/a/uWR4H
How can I fix the errors and make it look like the screenshot?

And is there any way to use terminal vim instead of gvim?

Thanks and keep it up!

**Comment by JBakamovic** [comment]
From the screenshot it seems like Python `watchdog` module is not properly installed. Can you try installing it manually for the distribution you're running and try running `yavide` once more?

Speaking of `vim` vs. `gvim`, I think it's not impossible but it is also not straightforward. One example is support for `clientserver` which by default, at least on F24, is not compiled into `vim` and that is amongst most important things that most other features rely upon. Of course you can give it a try and compile your own version of `vim` to include support for `clientserver` but I am not sure if that is the only thing which needs to be tweaked.

**Comment by ckubrak** [comment]
@JBakamovic thanks for your quick answer. I've just tried installing python watchdog (from arch official repositories and from pip) and even after rebooting, I'm still getting the same error. Just in case, this is my `vim --version`  https://gist.github.com/ckubrak/4f868c26deb76679f0902a56864c468c

**Comment by JBakamovic** [comment]
Can you please try running `import watchdog` or `from watchdog.observers import Observer` from interactive Python interpreter? I.e. run python from your console

Do you get errors there?

**Comment by ckubrak** [comment]
@JBakamovic I don't get any error when I run it with python 3.5 but I do get 

> ImportError: No module named watchdog.observers

when I run python 2.7
