### ISSUE TITLE
Error detected on start

### ISSUE THREAD

**Issue by JonyBepary** [JBakamovic/yavide#51]
at Start popup a window a give This.

Error detected while processing /opt/yavide/core/.core.vimrc: 
line   29: 
E319: Sorry, the command is not available in this version: python import sys, vim 
line   30: 
E319: Sorry, the command is not available in this version: python sys.path.append(vim.eval('g:YAVIDE_CORE_DIRECTORY')) 
Error detected while processing /opt/yavide/core/.globals.vimrc: 
line   59: 
E319: Sorry, the command is not available in this version: python << EOF 
line   60: 
E492: Not an editor command: from multiprocessing import Queue 
line   61: 
E492: Not an editor command: server_queue = Queue() 
line   62: 
E492: Not an editor command: EOF

**Comment by JBakamovic** [comment]
Can you check if your `gvim` instance has been compiled with `python` and/or `python3` support? You can check that by running `gvim --version | grep python`.

If it is then still some dependency is missing but solving it depends on the distro you are running.

**Comment by JonyBepary** [comment]
Problem solve After running running this command.

Instance of `vim` deployed on `Ubuntu 16.04` for example does not have compiled in the `python` support. To fix the issue on this Ubuntu system one can run the following commands:
    * `sudo apt install vim-gnome-py2`
    * `sudo update-alternatives --set vim /usr/bin/vim.gnome-py2`
    * `sudo update-alternatives --set gvim /usr/bin/vim.gnome-py2`

**Comment by nolanholden** [comment]
I am getting these exact same errors as @JonyBepary, and none of the three fixes seem to work for Ubuntu 17.04 (zesty). (It's worth noting that `vim-gnome-py2` does not exist, at least in apt, for Ubuntu 17.04 zesty.) This suggests a lack of support for Ubuntu 17.04 users.

Any suggestions?

As seen below in my `vim --version`, python (not python3) is listed, but has a `-` rather than a `+`
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 17 2017 12:13:35)
Included patches: 1-95
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     +tcl
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
+clientserver    +insert_expand   +packages        +toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xpm
+emacs_tags      +mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        +mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary
```

**Comment by JBakamovic** [comment]
> It's worth noting that vim-gnome-py2 does not exist, at least in apt, for Ubuntu 17.04 zesty.

I am not a Ubuntu user but according to [this page](https://launchpad.net/ubuntu/zesty/+package/vim-gnome-py2) it seems that it exists in the repository. Did you try running `sudo apt-get update` first?

I can also see that [someone else](https://www.thelinuxfaq.com/ubuntu/ubuntu-17-04-zesty-zapus/vim-gnome-py2) has done it as well.

**Comment by nolanholden** [comment]
Interesting, you're right. I'll try manually. Meantime, I updated and will update resolution in here: #77
