### ISSUE TITLE
How to do a vertical selection with yavide?

### ISSUE THREAD

**Issue by fabceolin** [JBakamovic/yavide#58]
How to do a vertical selection with yavide with default configuration?

I am trying to use Ctrl K + Ctrl V without success.

Thanks

**Comment by JBakamovic** [comment]
Try using `Ctrl K` + `Ctrl Q` instead. See `:help visual-block` and `:help CTRL-V-alternative` for more details. `Ctrl P` is used to paste text instead in `yavide`.
