### ISSUE TITLE
F7 build doesn't do anything

### ISSUE THREAD

**Issue by Paludan** [JBakamovic/yavide#67]
I may not fully understand exactly what the :YavineBuildRun is supposed to do, however running it doesn't open a new buffer with it being run in. Is there anything specific this command is supposed to do? Also it doesn't provide me with a *.out file or anything.

Cheers.

**Comment by JBakamovic** [comment]
Please have a look at [project builder](https://github.com/JBakamovic/yavide/blob/master/docs/services_framework.md#project-builder) section. You need to set `g:project_env_build_command` variable to the build command which corresponds to the build system you are using (e.g. `make`).

**Comment by kross23** [comment]
I have a similar problem after pressing F7, the message || make: *** There is no rule for assembling the goal "all". Stop. as I understand the reason in the file.

let g: project_root_directory = '/ home / kross / shok / shokolad'
let g: project_name = 'shokolad'
let g: project_category = 2
let g: project_type = 3
let g: project_env_build_preproces_command = ''
let g: project_env_build_command = ''
let g: project_env_compilation_db_path = "
I just do not know what to prescribe
I apologize if my question seems stupid I recently began to study with ++.
or problem in | QuickFixCmdPre | what and how to set up?
or most to make a makefile? but how to do it automatically?
How to run the program in a yavide as a simple ide?

**Comment by kross23** [comment]
[compile_flags.txt](https://github.com/JBakamovic/yavide/files/1690123/compile_flags.txt)

**Comment by JBakamovic** [comment]
Excerpt from existing [documentation](https://github.com/JBakamovic/yavide/blob/master/docs/services_framework.md#configuration):
> compile_flags.txt which contains all the compiler flags relevant for your project (**one compiler flag per line**).

File you attached breaks _one-compiler-flag-per-line_ rule. This file should also contain compile flags relevant for the project you're building and not the ones I have put as an example (which seems you only c/p).
