### ISSUE TITLE
No uninstallation script

### ISSUE THREAD

**Issue by prateeksingh0001** [JBakamovic/yavide#68]
@JBakamovic I started using Yadive and liked it plenty. But now I am trying out some other configurations for vim and which require uninstallation of yavide. 
Nowhere I could find the resource stating the process of uinstallation. It would be very helpful if you could guide me towards the above.

**Comment by JBakamovic** [comment]
You should be able to try out anything else without uninstalling it. `Yavide` installation does not affect your local vim configuration. Everything is self-contained within a single (installation) directory.

However, if you wish to remove it you could have a look at [install.sh](https://github.com/JBakamovic/yavide/blob/master/install.sh) for full overview what is being installed but in general it should be no more than removing the:
1. Installation directory
2. `yavide.desktop` from `/usr/share/applications` and from `~/Desktop`
3. `yavide` alias from `~/.bashrc`

**Comment by prateeksingh0001** [comment]
@JBakamovic Thanks alot, that was really helpful :) .
