### ISSUE TITLE
Cant find <yavide_install_dir>/core/.globals.vimrc

### ISSUE THREAD

**Issue by yoyomanyoyo87** [JBakamovic/yavide#69]
Does not appear in my Core folder.

**Comment by JBakamovic** [comment]
Sounds really strange as this particular file (and not only the file but the whole directory) is being copied over to the installation directory: [here](https://github.com/JBakamovic/yavide/blob/master/install.sh#L202).

Were there any errors during the installation? It might be that the file(s) is still there but under another path. Can you check if installation directory contains the files as the cloned repo?

**Comment by yoyomanyoyo87** [comment]
Nevermind, they were hidden from `ls`. I had to use `ls -a` because they were dotfiles.
