### ISSUE TITLE
Loop password request.

### ISSUE THREAD

**Issue by Dumbeldor** [JBakamovic/yavide#71]
During installation the password is requested loop.
(Using the installation.sh script)

![capture du 2017-06-25 02-03-05](https://user-images.githubusercontent.com/3883583/27512711-a5f352be-594a-11e7-9c16-d9bd874506ba.png)

**Comment by JBakamovic** [comment]
Installation failed or? What system are you running? What terminal?

**Comment by Dumbeldor** [comment]
I re-launched the script and I had no worries.
I'm on archlinux, the terminal is zsh with oh my zsh.
